### ISSUE TITLE
Use computed color of `--fgColor-muted` for injected elements

### ISSUE THREAD

**Issue by uncenter** [yuyinws/refined-github-file-nesting#1]
I use a userstyle to use a different palette on GitHub, and since the colors of this userscript are hardcoded it doesn't match. Maybe the userscript could get the computed value of GitHub's `--fgColor-muted` CSS variable and use that for the icon and text color?

**Comment by yuyinws** [comment]
Good suggestion! It has been implemented in [v0.0.7](https://greasyfork.org/zh-CN/scripts/519923-refined-github-file-nesting)
